#on:
  #reddit:
    #url: https://www.reddit.com/r/FreeEBOOKS+freebooks
#jobs:
  #telegram:
    #name: Send a telegram message2
    #runs-on: ubuntu-latest
    #steps:
      #- name: Send a telegram message
      #  uses: appleboy/telegram-action@master
      #  with:
      #    to: ${{ secrets.TELEGRAM_TO }}
      #    token: ${{ secrets.TELEGRAM_TOKEN }}
      #   #format: html
      #    message:  |
       #     ${{on.reddit.outputs.title}}
         #   ${{on.reddit.outputs.content}
on:
  reddit:
    url: https://www.reddit.com/r/news/
    source: json
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: $<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
          subr: $<a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">by {{on.reddit.outputs.subreddit_name_prefixed}}</a>
          author: $<a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a>
          url: $<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>
          #plink: 
        run: |
          echo title: $title
          echo url: $url
          echo subr: $subr
          echo author: $author
          #echo plink: 
          
          #<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
          #<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a><a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a> <a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">at {{on.reddit.outputs.subreddit_name_prefixed}}</a>
