on:
  reddit:
    url: https://www.reddit.com/r/FreeEBOOKS+freebooks
    source: json
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: HTML
          message:  |
            <b>${{on.reddit.outputs.title}}</a></b>
            <a href="${{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>
            Via <a href="https://reddit.com${{on.reddit.outputs.permalink}}">${{on.reddit.outputs.subreddit_name_prefixed }}</a> By ${{on.reddit.outputs.author }}
