#on:
  #reddit
    #url: https://www.reddit.com/r/FreeEBOOKS+freebooks
    #source: json
#jobs:
  #telegram:
    #name: Send a telegram message2
    #runs-on: ubuntu-latest
    #steps:
      #- name: Send a telegram message
      #  uses: appleboy/telegram-action@master
      #  with:
      #    to: ${{ secrets.TELEGRAM_TO }}
      #    token: ${{ secrets.TELEGRAM_TOKEN }}
      #    format: html
      #    message:  |
       #     <b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
         #   <a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">by {{on.reddit.outputs.subreddit_name_prefixed}}</a>
         #   $<a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a>
         #   $<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>
on:
  reddit:
    url: https://www.reddit.com/r/news/
    source: json
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: $<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
          subr: $<a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">by {{on.reddit.outputs.subreddit_name_prefixed}}</a>
          author: $<a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a>
          url: $<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>
          #plink: ${{on.reddit.outputs.permalink}}
        run: |
          echo title: <b><a href="https://www.reddit.com$plink">$title</a></b>$title
          echo url: <a href="$url">Book Link</a>
          echo subr: $subr
          echo author: <a href="$author">Book Link</a>
            #<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
            #<a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">by {{on.reddit.outputs.subreddit_name_prefixed}}</a>
            #$<a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a>
            #-$<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>          
          
          #<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
          #<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a><a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a> <a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">at {{on.reddit.outputs.subreddit_name_prefixed}}</a>
