on:
  reddit:
    url: https://www.reddit.com/r/FreeEBOOKS+freebooks
    source: json
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: HTML
          message:  |
            ${{on.reddit.outputs.title}}
            https://www.reddit.com${{on.reddit.outputs.permalink}}
            by ${{on.reddit.outputs.subreddit_name_prefixed}}
            ${{on.rss.outputs.contentSnippet}}
            ${{on.reddit.outputs.author }}
            ${{on.reddit.outputs.url_overridden_by_dest}}

          
          #message:  |
            #echo <b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">${{on.reddit.outputs.title}}</a></b>
            #echo <a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">by ${{on.reddit.outputs.subreddit_name_prefixed}}</a>
            #echo <a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by ${{on.reddit.outputs.author }}</a>
            #echo <a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>
#on:
  #reddit:
    #url: https://www.reddit.com/r/news/
    #source: json
#jobs:
  #print:
    #name: Print
    #runs-on: ubuntu-latest
    #steps:
      #- name: Print Outputs
        #env:
          #title: ${{on.reddit.outputs.title}}
          #subr: ${{on.reddit.outputs.subreddit_name_prefixed }}
          #url: ${{on.reddit.outputs.url_overridden_by_dest}}
          #plink: ${{on.reddit.outputs.permalink}}
          #author: ${{on.reddit.outputs.author }}
        run: |
          echo title: $title
          echo sub: https://www.reddit.com/$subr
          echo url: $url
          echo plink: https://www.reddit.com/$plink
          echo author: https://www.reddit.com/user/${{on.reddit.outputs.author}}

            #<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
            #<a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">by {{on.reddit.outputs.subreddit_name_prefixed}}</a>
            #$<a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a>
            #-$<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>    
            #$<a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a>
          
          #<b><a href="https://www.reddit.com${{on.reddit.outputs.permalink}}">{{on.reddit.outputs.title}}</a></b>
          #<a href="{{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a><a href="https://www.reddit.com/user/${{on.reddit.outputs.author}}">by {{on.reddit.outputs.author }}</a> <a href="https://www.reddit.com/${on.reddit.outputs.subreddit_name_prefixed}}">at {{on.reddit.outputs.subreddit_name_prefixed}}</a>
