#on:
  #reddit:
    #url: https://www.reddit.com/r/FreeEBOOKS+freebooks
#jobs:
  #telegram:
    #name: Send a telegram message2
    #runs-on: ubuntu-latest
    #steps:
      #- name: Send a telegram message
      #  uses: appleboy/telegram-action@master
      #  with:
      #    to: ${{ secrets.TELEGRAM_TO }}
      #    token: ${{ secrets.TELEGRAM_TOKEN }}
      #   #format: html
      #    message:  |
       #     ${{on.reddit.outputs.title}}
         #   ${{on.reddit.outputs.content}
on:
  reddit:
    url: https://www.reddit.com/r/news/
    source: json
    #config:
      #limit: 15
      #source: json
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.reddit.outputs.title}}
          sub: https://www.reddit.com/user/${{on.reddit.outputs.subreddit_name_prefixed }}
          url: ${{on.reddit.outputs.url_overridden_by_dest}}
          link: https://www.reddit.com${{on.reddit.outputs.permalink}}
        run: |
          echo title: $title
          echo link: $sub
          echo link: $url
          echo link: $link
