on:
  reddit:
    url:
      https://www.reddit.com/r/FreeEBOOKS/
      https://www.reddit.com/r/freebooks/
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:  |
          title: ${{on.reddit.outputs.title}}
          content: ${{on.reddit.outputs.content}}
          link: ${{on.reddit.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $content
          echo link: $link
