runs:
  using: 'node20'
  pre: 'setup.js'
  main: 'index.js'
  post: 'cleanup.js'
  on:
    reddit:
    url: https://www.reddit.com/r/FreeEBOOKS+freebooks
    source: json
    schedule:
    - cron: "*/15 * * * *"
    config:
      limit: 15
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: HTML
          disable_web_page_preview: false
          message:  |
            <b>${{on.reddit.outputs.title}}</b>
            Via <a href="https://reddit.com/${{on.reddit.outputs.permalink}}">${{on.reddit.outputs.subreddit_name_prefixed }}</a> By ${{on.reddit.outputs.author }}
            <a href="${{on.reddit.outputs.url_overridden_by_dest}}">Book Link</a>
          
